# Generated by Django 4.2.4 on 2023-09-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название задачи')),
                ('contestId', models.IntegerField(verbose_name='Id соревнования')),
                ('index', models.CharField(max_length=10, verbose_name='Индекс задачи')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество баллов за задачу')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг задачи (сложность)')),
                ('type_problem', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип задачи')),
                ('solved_count', models.IntegerField(blank=True, null=True, verbose_name='Число решений задачи')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тэг')),
                ('problem', models.ManyToManyField(to='parsing.problems', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
            },
        ),
        migrations.CreateModel(
            name='SendedProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimesend', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.problems', verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'отправленная задача',
                'verbose_name_plural': 'отправленные задачи',
            },
        ),
    ]
