# Generated by Django 4.2.4 on 2023-09-10 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parsing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название контеста')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Описание контеста')),
            ],
            options={
                'verbose_name': 'контест',
                'verbose_name_plural': 'контесты',
            },
        ),
        migrations.AlterUniqueTogether(
            name='problems',
            unique_together={('contestId', 'index')},
        ),
        migrations.CreateModel(
            name='BotMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='id сообщения')),
                ('message_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='текст сообщения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AddField(
            model_name='problems',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.contest', verbose_name='Контест'),
        ),
    ]
