# Generated by Django 4.2.4 on 2023-09-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_subscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
